# Generated by Django 4.1.4 on 2023-01-15 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3)),
                ('account_name', models.CharField(max_length=10)),
                ('amount_check', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ('id', 'user', 'currency', 'account_name', 'amount_check'),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=10)),
                ('token', models.CharField(max_length=16, null=True)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ('user_id', 'full_name', 'token', 'date'),
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_categories', models.CharField(default=None, max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.user')),
            ],
            options={
                'ordering': ('user', 'user_categories'),
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_of_income', models.CharField(max_length=10)),
                ('amount_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.account')),
            ],
            options={
                'ordering': ('source_of_income', 'amount_income', 'account_id', 'date'),
            },
        ),
        migrations.CreateModel(
            name='FamilyUser',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=10)),
                ('family_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.user')),
            ],
            options={
                'ordering': ('family_user_id', 'user_id', 'full_name'),
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=50)),
                ('amount_expenses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.account')),
            ],
            options={
                'ordering': ('category', 'title', 'amount_expenses', 'account_id', 'date'),
            },
        ),
        migrations.CreateModel(
            name='CategoryLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=15)),
                ('amount_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.account')),
            ],
            options={
                'ordering': ('id', 'account_id', 'name_category', 'amount_limit'),
            },
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.user'),
        ),
    ]
